# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  ...
}:
{
  networking = {
    useDHCP = lib.mkDefault true;
    interfaces.end0.useDHCP = lib.mkDefault true;
    interfaces.wlan0.useDHCP = lib.mkDefault true;

    #firewall.allowedTCPPorts = [ ... ];
    #firewall.allowedUDPPorts = [ ... ];
    firewall.enable = true;
  };
}
