name: "Build Check"
on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            host: kratos
          - os: ubuntu-latest
            host: blade
          - os: ubuntu-latest
            host: nixbook
          - os: ubuntu-latest
            host: inix
          - os: ubuntu-latest
            host: kronos
          - os: ubuntu-24.04-arm
            host: hermes
    runs-on: ${{ matrix.os }}
    steps:
      # Check out the branch
      - uses: actions/checkout@v6
      # clean up/recover free space
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'cleave'  # Options: holster, carve, cleave (default), rampage
      # enable ssh agent for accessing private repo
      - uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # install nix
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra_nix_config: |
            build-dir = /nix/build
      # cache nix in Github
      - uses: DeterminateSystems/magic-nix-cache-action@main
      # enable cachix support
      - uses: cachix/cachix-action@v17
        with:
          name: deidrael
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
  
      # build system
      - name: Build
        run: nix build -L .#nixosConfigurations.${{matrix.host}}.config.system.build.toplevel
  
      # push back to cachix
      - name: Deploy
        run: |
          cachix push deidrael ./result*
